------------------------------------------------------
/* CONTINUOUS SAIL GP LOOK UP */
------------------------------------------------------
CREATE TABLE SAILW1658V.LB_SAIL_GP_REG_LOOKUP (ALF_PE BIGINT,
START_DATE DATE,
END_DATE DATE,
ISLAND_ID INTEGER);

INSERT
	INTO
	SAILW1658V.LB_SAIL_GP_REG_LOOKUP
SELECT
	ALF_PE,
	MIN(START_DATE),
	MAX(END_DATE),
	ISLAND_ID
FROM
	(
	SELECT
		*,
		CASE
			WHEN START_DATE = LAG(END_DATE + 1) OVER(PARTITION BY ALF_PE
		ORDER BY
			ALF_PE,
			START_DATE) THEN 0
			ELSE 1
		END AS CONT_FLAG,
		SUM(CASE WHEN START_DATE = LAG(END_DATE + 1) OVER(PARTITION BY ALF_PE ORDER BY ALF_PE, START_DATE) THEN 0 ELSE 1 END) OVER(PARTITION BY ALF_PE
	ORDER BY
		ALF_PE,
		START_DATE) AS ISLAND_ID
	FROM
		SAIL1658V.WLGP_CLEAN_GP_REG_BY_PRAC_INCLNONSAIL_MEDIAN_20240101 S
	WHERE
		GP_DATA_FLAG = 1
	ORDER BY
		ALF_PE,
		START_DATE )
GROUP BY
	ALF_PE,
	ISLAND_ID
ORDER BY
	ALF_PE;