---------------------------------------
---- RCT matching cohort creation
---------------------------------------
-- Step 1: Linkage
	-- 1.1 Link WDSD to geog to get WIMD
	-- 1.2 Link to rural urban to get RUC
	-- 1.3 Link to ADDE to get death date
	-- 1.4 Remove records where ALF is in RCT's reablement cohort (LB_COHORT_RCT)
-- Step 2: Cleaning
	
	-- 2.1 Remove records where GNDR_CD not in 1 or 2
	-- 2.3 Remove records with NULL WOB
	-- 2.4 Remove records with NULL LSOA 
	-- 2.5 Remove records not resident in RCT
	-- 2.6 Remove records with DEATH_DT before study start (1st April 2022)


DROP TABLE SAILW1658V.JP_MATCHING_COHORT_RCT;

CREATE TABLE SAILW1658V.JP_MATCHING_COHORT_RCT (
	ALF_PE BIGINT,	
	WOB DATE,
	GNDR_CD INTEGER,
	LSOA2011_CD VARCHAR(10),
	LSOA_DESC VARCHAR(17),
	WIMD_2019_QUINTILE INTEGER,
	RUC11CD CHARACTER(2),
	RUC11 VARCHAR(47),
	DEATH_DT DATE,
	START_DT DATE,
	END_DT DATE
);

INSERT INTO SAILW1658V.JP_MATCHING_COHORT_RCT
SELECT DISTINCT W.ALF_PE,
	W.WOB,
	W.GNDR_CD,
	G.LSOA2011_CD,
	G.LSOA_DESC,
	G.WIMD_2019_QUINTILE,
	R.RUC11CD,
	R.RUC11,
	D.DEATH_DT, 
	G.START_DATE,
	G.END_DATE	
FROM SAIL1658V.WDSD_SINGLE_CLEAN_AR_PERS_20240408 W
-- 1.1 Link to geog to get WIMD
LEFT JOIN SAIL1658V.WDSD_SINGLE_CLEAN_GEO_CHAR_LSOA2011_20240408 G 
	ON W.ALF_PE = G.ALF_PE
-- 1.2 Link to rural urban to get RUC
LEFT JOIN SAILREFRV.RURAL_URBAN_CLASS_2011_OF_LLSOAREAS_IN_ENG_AND_WAL R 
	ON G.LSOA2011_CD = R.LSOA11CD 
-- 1.3 Link to ADDE to get death date
LEFT JOIN SAIL1658V.ADDE_DEATHS_20240401 D
	ON W.ALF_PE = D.ALF_PE;

-- 1.4 Remove records in LB_COHORT_RCT
DELETE FROM SAILW1658V.JP_MATCHING_COHORT_RCT
WHERE ALF_PE IN (SELECT DISTINCT ALF_PE FROM SAILW1658V.LB_COHORT_RCT); 


-- Check remaining row count
SELECT COUNT(*)
FROM SAILW1658V.JP_MATCHING_COHORT_RCT; 

-- 2.1 Remove records where GNDR_CD not NULL or in 1 or 2
DELETE FROM SAILW1658V.JP_MATCHING_COHORT_RCT
WHERE GNDR_CD NOT IN(1,2) OR GNDR_CD IS NULL;

-- Check remaining row count
SELECT COUNT(*)
FROM SAILW1658V.JP_MATCHING_COHORT_RCT; 

-- 2.2 Remove records with NULL WOB
DELETE FROM SAILW1658V.JP_MATCHING_COHORT_RCT
WHERE WOB IS NULL; 

-- 2.3 Remove records with NULL LSOA 
DELETE FROM SAILW1658V.JP_MATCHING_COHORT_RCT
WHERE LSOA2011_CD IS NULL; 

-- Check remaining row count
SELECT COUNT(*)
FROM SAILW1658V.JP_MATCHING_COHORT_RCT; 

-- 2.4 Remove records not resident in RCT 
DELETE FROM SAILW1658V.JP_MATCHING_COHORT_RCT
WHERE LSOA_DESC != 'Rhondda Cynon Taf' OR LSOA_DESC IS NULL; 

-- Check remaining row count
SELECT COUNT(*)
FROM SAILW1658V.JP_MATCHING_COHORT_RCT;

-- 2.5 Remove records with DEATH_DT before 1st April 2022
DELETE FROM SAILW1658V.JP_MATCHING_COHORT_RCT
WHERE DEATH_DT < '2022-04-01'; 


SELECT COUNT(*)
FROM SAILW1658V.JP_MATCHING_COHORT_RCT; 

SELECT COUNT(UNIQUE(ALF_PE))
FROM SAILW1658V.JP_MATCHING_COHORT_RCT; 

